### Model Specification
model:
  backbone: CheapBackbone
  model_dim: 512
  blocks: 6
  iterations: 5
  vertices: 128
### Training configuration
seed: 27
loss_function: Huber
loss_stepwise: true
### Data args
batch_size: 32
samples_per_image: 8
