### Model Specification
model:
  backbone: Xception
  model_dim: 512
  iterations: 5
  vertices: 128
### Training configuration
seed: 27
loss_function: Huber
loss_stepwise: true
### Data args
batch_size: 16
samples_per_image: 32
