### Model Specification
model:
  backbone: Xception
  model_dim: 1024
  blocks: 6
  iterations: 5
  vertices: 128
### Training configuration
seed: 27
loss_function: Huber
loss_stepwise: true
### Data args
batch_size: 8
samples_per_image: 8
