### Model Specification
model: COBRA
model_args:
  backbone: Xception
  model_dim: 1024
  iterations: 4
  coord_features: true
  stop_grad: true
  weight_sharing: true
  head: SnakeHead
### Training configuration
seed: 27
loss_function: huber
loss_stepwise: true
### Data args
batch_size: 12
vertices: 128
