### Model Specification
model:
  backbone: Xception
  model_dim: 128 # simplify 1024
  iterations: 2 # simplify 5
  vertices: 128
### Training configuration
seed: 27
loss_function: Huber
loss_stepwise: true
### Data args
batch_size: 8
